### ISSUE TITLE
Is Transcrypt dead?

### ISSUE THREAD

**Issue by faerot** [TranscryptOrg/Transcrypt#650] opened 2019-07-03 14:27 UTC
It's been 6 months since Jacques reacted on any of reported issues and I am wondering what are his plans about the future of this project. I am currently working on a pretty large project based heavily on Transcrypt and cannot drop it mid-way, therefore I am wondering if I should look forward to updates or just make a fork and try to fix all the reported issues on my own somehow (I am not very good at JavaScript).

**Comment by JdeH** [comment] 2019-07-03 14:46
NO!! I just had some other projects for customers that took up lots of time. But Transcrypt is as alive as ever. In fact it is quite high on my priority list, and I plan to start working on it again in fall for a considerable part of my time. But earning an income sometimes takes priority. 

I assure you that I will be working on Transcrypt for many years to come, assuming I'll live in good health. I'm thinking about 5 years at least, but I'd like 10 better. And I also plan to transfer it in a responsible way, should it ever be necessary. Meanwhile I  hope I can again count on the cooperation of other developers, that made such great contributions in the past.

Transcrypt for me isn't a hobby but something I also rely on for my professional work.


Kind regards
Jacques

**Comment by faerot** [comment] 2019-07-03 18:21
Great news, I will keep on reporting bugs then :)

**Comment by JdeH** [comment] 2019-07-03 18:45
Thanks, and sorry I got you worried like this.

**Comment by kaymccormick** [comment] 2019-08-09 21:48
I've been working on my own Python-to-typescript compiler since I have been unable to get Transcrypt to work, and it seemed like less work to do it on my own than to figure out how someone else engineered their compiler. But, it is clearly quite some work to be done, and while I have been having fun on the project, it doesn't seem like a good use of time since it appears you've done all the work. I just can't seem to put your work to good use.

**Comment by fzzylogic** [comment] 2019-08-10 03:13
@kaymccormick Hi, thanks for the feedback, not sure which parts aren't working for you, which OS you're on etc. New issue might be needed. But pressing on, installed the latest Transcrypt (using Windows 10) from [doc instructions](https://www.transcrypt.org/docs/html/installation_use.html#installation). If new to python and pip, be sure to read the link with a very clear and brief introduction to pip.

Autotests are still failing as reported in [604](https://github.com/QQuick/Transcrypt/issues/604). And there may also be some things in the docs that need updating, so would be good to know any issues you've bumped into. Also, it's a bit of a thing to have it work across OS's, so any OS specific issues you come across can also help smooth things out for others in future.

To do a basic compile test, I followed the instructions under ["Your first Transcrypt program"](https://www.transcrypt.org/docs/html/installation_use.html#your-first-transcrypt-program). An exact walk-through to get to that point might be helpful as that can help to identify things that might have slipped between the cracks. (Windows command prompt):

mkdir transcrypt_test
cd transcrypt_test

python --version
:: > Python 3.7.2

:: If you have multiple versions, on Windows the one to use
:: can be selected using the py launcher, e.g. 'py -37'

:: Create a virtual env, placing it in the 'wenv' folder
:: On linux systems i like to create a 'lenv' folder, so
:: two virtual env's can co-exist in the same place.
python -m venv wenv

:: Activate the virtual env
:: On linux / mac (bash) this would be: source lenv/bin/activate
:: Once activated, one can use 'python' to refer to python, even
:: if there are multiple system versions installed.
wenv\Scripts\activate

:: Just in case, ensure the virtual env contains the latest versions of 
:: pip and setuptools (one can upgrade this globally from an
:: elevated prompt, but we'll just focus on the current virtual env)
python -m pip install --upgrade pip setuptools

:: Install the latest Transcrypt in the virtual env.
:: On ubuntu linux one may first need 'apt-get install python3-dev'
pip install transcrypt

:: Make the two files, 'hello.html' and 'hello.py' by cutting and
:: pasting from the docs above.

:: Compile hello.py to js. That should output files in the '__target__' dir.
transcrypt hello

:: Run a simple http server, then view the files in your browser
:: at localhost:8000
python -m http.server 8000

**Comment by JdeH** [comment] 2019-08-14 11:48
@kaymccormick Did the docs pointed to by @fzzylogic provide enough info? Did you get it to work? Or are there still problems?

**Comment by Andrei-Pozolotin** [comment] 2019-09-19 14:50
@JdeH Jacques:
* just as a proof of life: please make release? :-)
* previous release is about 1 year old
* thank you

**Comment by JdeH** [comment] 2019-09-22 08:52
@Andrei-Pozolotin 

Hi Andrei,

I am currently looking into issue #574, and after that maybe a tiny bit of low hanging fruit.
Subsequently there'll be a release, indication in about 1 month, earlier if doable.

In general it would be good to return to a more frequent release scheme, say every three months or so.
The switch to JS modules costed a lot of time and energy, which meant I incurred a backlog with other activities, but that's now dealth with.

So there will be more frequent "proofs of life" ;)

KR
Jacques

**Comment by Andrei-Pozolotin** [comment] 2019-09-24 16:50
great, thank you

**Comment by Andrei-Pozolotin** [comment] 2019-11-04 16:37
@JdeH Jacques:
curious: will [dev_fall_2019](https://github.com/QQuick/Transcrypt/commits/dev_fall_2019) will make it in the fall of 2019?

**Comment by JdeH** [comment] 2019-11-06 16:59
@Andrei-Pozolotin 

To be honest: due to some (temporary) personal circumstances it very well might not.
I'd like to have included some Python 3.8 stuff, but that'll probably have to wait until early next year.

Currently I am moving Transcrypt development from Windows to (Arch) Linux, which is costing more time than expected. But the benefits should outweight the effort, recently I lost weeks worth of work (not Transcrypt related) through one of W10's automated updates, so I decided it's becoming too big a risk.

So: some setbacks, especially since multiple team members are very busy at the moment. Maybe the  team should be expanded, but that will also result in more overhead. I have been thinking about that for quite some time, but not really reached a solution. The problem is that only really proficient, proactive developers will alleviate the work, otherwise I'll just spent more time reviewing PR's.

What's wisdom here... I don't know yet. Working with volunteers means working with an ever changing crew. I am amazed about the amount of work and experience some devs have been putting in. But usually they have quite a lot of balls to keep in the air...

**Comment by Andrei-Pozolotin** [comment] 2019-11-08 17:12
@JdeH Jacques:

1. great, thank you for the update. 
P.S.: I also moved from Windows to Arch Linux many years back :-)

2. Regarding the project development strategy: perhaps you could open a project forum discussion
and invite people to contribute their ideas, including how much time can they commit to the project.
For example: I personally can commit 2 hr per week, `iff` I have clear guidance form you and a promise from you to accept/reject the PR in the 4 week window since submission of the PR.

**Comment by mymi14s** [comment] 2019-11-15 20:21
@jdeh how can I be of help to this project, I am a python/Django developer and honestly, Transcrypt has made my work easier since am poor in Javascript. I'd love Transcrypt to stay alive, grow and get popular. I googled how I can integrate it with Django, found no result then decided to try my own solution, it worked like magic.

Honestly I am more productive with Transcrypt. Please let me know the area I can be of help.

**Comment by metaperl** [comment] 2021-04-06 13:36
@mymi14s - are you still interested? #604 has still not been resolved. Maybe fork and re-release?

**Comment by JennaSys** [comment] 2023-04-23 08:23
Closing since no further comments.

**Closed by JennaSys** 2023-04-23 08:23 UTC
Labels: NEED: feedback
